@extends('layouts.app')

@section('content')
<div class="min-h-screen bg-gradient-to-br from-indigo-50 to-purple-100">
    <div class="container mx-auto px-4 py-6 max-w-6xl">
        
        <!-- Mobile Header -->
        <div class="mb-8">
            <div class="flex flex-col md:flex-row md:justify-between md:items-center space-y-4 md:space-y-0">
                <div class="animate-fade-in">
                    <h1 class="text-2xl md:text-3xl font-bold text-gray-900 mb-2">
                        {{ $isFrench ? 'Analyse Sherlock' : 'Sherlock Analysis' }}: {{ $month_name }}
                    </h1>
                    <div class="flex flex-wrap items-center space-x-4 text-sm text-gray-600">
                        <div class="flex items-center space-x-2">
                            <svg class="w-5 h-5 text-indigo-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"></path>
                            </svg>
                            <span>{{ $isFrench ? 'Période analysée' : 'Analysis period' }}: {{ $month_name }}</span>
                        </div>
                        <div class="flex items-center space-x-2">
                            <svg class="w-5 h-5 text-indigo-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                            </svg>
                            <span>{{ $isFrench ? 'Généré le' : 'Generated on' }}: {{ now()->format('d/m/Y H:i') }}</span>
                        </div>
                    </div>
                </div>
                
                <div class="flex flex-col md:flex-row space-y-2 md:space-y-0 md:space-x-2 animate-fade-in delay-100">
                    <button onclick="window.print()" 
                            class="bg-gray-800 text-white px-4 py-2 rounded-lg hover:bg-gray-700 transition-colors duration-200 flex items-center justify-center space-x-2">
                        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"></path>
                        </svg>
                        <span>{{ $isFrench ? 'Imprimer' : 'Print' }}</span>
                    </button>
                    @include('buttons')
                </div>
            </div>
        </div>

        <!-- Analysis Results Card -->
        <div class="bg-white rounded-2xl shadow-xl overflow-hidden animate-scale-in">
            <div class="bg-gradient-to-r from-indigo-600 to-purple-700 px-6 py-6">
                <h2 class="text-xl font-semibold text-white flex items-center">
                    <svg class="w-6 h-6 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
                    </svg>
                    {{ $isFrench ? 'Rapport d\'analyse IA' : 'AI Analysis Report' }}
                </h2>
                <p class="text-indigo-100 mt-2">
                    {{ $isFrench ? 'Analyse générée automatiquement par Sherlock' : 'Analysis automatically generated by Sherlock' }}
                </p>
            </div>
            
            <div class="p-6 md:p-8">
                <!-- Analysis Content -->
                <div class="sherlock-analysis markdown-content prose prose-lg max-w-none animate-fade-in-up">
                    <div class="text-gray-800 leading-relaxed">
                        {{-- Utilisation de Str::markdown() pour convertir le Markdown en HTML --}}
                        {!! Str::markdown($analysis) !!}
                    </div>
                </div>
            </div>
        </div>
        
        <!-- Debug Section (only if raw_data exists) -->
        @if(isset($raw_data))
            <div class="mt-8 bg-gray-100 rounded-2xl border border-gray-200 overflow-hidden animate-fade-in-up delay-200">
                <div class="bg-gray-200 px-6 py-4 border-b border-gray-300">
                    <h3 class="text-lg font-medium text-gray-900 flex items-center">
                        <svg class="w-5 h-5 mr-2 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4"></path>
                        </svg>
                        {{ $isFrench ? 'Données brutes (debug)' : 'Raw data (debug)' }}
                    </h3>
                </div>
                <div class="p-6">
                    <div class="bg-gray-900 rounded-lg p-4 overflow-auto max-h-96">
                        <pre class="text-green-400 text-xs font-mono">{{ json_encode($raw_data, JSON_PRETTY_PRINT) }}</pre>
                    </div>
                </div>
            </div>
        @endif
    </div>
</div>

<style>
/* Print Styles */
@media print {
    nav, header, footer, .hidden-print, button {
        display: none !important;
    }
    
    body {
        background: white !important;
        font-size: 12pt;
        color: black !important;
    }
    
    .sherlock-analysis {
        page-break-inside: auto;
    }
    
    h1, h2, h3, h4, h5, h6 {
        page-break-after: avoid;
        color: black !important;
    }
    
    .markdown-content h1 {
        font-size: 18pt;
        margin-top: 20pt;
        margin-bottom: 10pt;
        font-weight: bold;
    }
    
    .markdown-content h2 {
        font-size: 16pt;
        margin-top: 15pt;
        margin-bottom: 8pt;
        font-weight: bold;
    }
    
    .markdown-content h3 {
        font-size: 14pt;
        margin-top: 12pt;
        margin-bottom: 6pt;
        font-weight: 600;
    }
    
    .markdown-content h4 {
        font-size: 13pt;
        margin-top: 10pt;
        margin-bottom: 5pt;
        font-weight: 600;
    }
    
    .markdown-content p, 
    .markdown-content ul, 
    .markdown-content ol,
    .markdown-content blockquote {
        margin-bottom: 8pt;
        color: black !important;
    }
    
    .markdown-content pre,
    .markdown-content code {
        background: #f5f5f5 !important;
        color: black !important;
        border: 1px solid #ddd !important;
    }
    
    .bg-white {
        background: white !important;
        box-shadow: none !important;
    }
    
    .container {
        max-width: 100% !important;
        margin: 0 !important;
        padding: 0 !important;
    }
}

/* Enhanced Markdown Styles */
.markdown-content {
    line-height: 1.7;
}

.markdown-content h1,
.markdown-content h2,
.markdown-content h3,
.markdown-content h4,
.markdown-content h5,
.markdown-content h6 {
    margin-top: 2rem;
    margin-bottom: 1rem;
    font-weight: 600;
    line-height: 1.3;
}

.markdown-content h1 {
    font-size: 2rem;
    color: #1e40af;
    border-bottom: 3px solid #3b82f6;
    padding-bottom: 0.75rem;
    margin-top: 0;
}

.markdown-content h2 {
    font-size: 1.75rem;
    color: #1e3a8a;
    border-bottom: 2px solid #6366f1;
    padding-bottom: 0.5rem;
}

.markdown-content h3 {
    font-size: 1.5rem;
    color: #3730a3;
    border-bottom: 1px solid #e5e7eb;
    padding-bottom: 0.25rem;
}

.markdown-content h4 {
    font-size: 1.25rem;
    color: #4338ca;
}

.markdown-content h5 {
    font-size: 1.125rem;
    color: #5b21b6;
}

.markdown-content h6 {
    font-size: 1rem;
    color: #6b21a8;
    font-weight: 700;
}

.markdown-content p {
    margin-bottom: 1.25rem;
    text-align: justify;
    color: #374151;
}

.markdown-content ul,
.markdown-content ol {
    margin: 1.25rem 0;
    padding-left: 2rem;
}

.markdown-content ul {
    list-style-type: disc;
}

.markdown-content ol {
    list-style-type: decimal;
}

.markdown-content li {
    margin-bottom: 0.75rem;
    line-height: 1.6;
    color: #374151;
}

.markdown-content li > ul,
.markdown-content li > ol {
    margin: 0.5rem 0;
}

.markdown-content blockquote {
    border-left: 4px solid #6366f1;
    background: #f8fafc;
    margin: 1.5rem 0;
    padding: 1rem 1.5rem;
    font-style: italic;
    color: #4b5563;
    border-radius: 0 0.5rem 0.5rem 0;
}

.markdown-content blockquote p {
    margin-bottom: 0.75rem;
}

.markdown-content blockquote p:last-child {
    margin-bottom: 0;
}

.markdown-content code {
    background: #f1f5f9;
    color: #e11d48;
    padding: 0.25rem 0.5rem;
    border-radius: 0.375rem;
    font-family: 'Monaco', 'Menlo', 'Ubuntu Mono', monospace;
    font-size: 0.875em;
    font-weight: 600;
}

.markdown-content pre {
    background: #1e293b;
    color: #e2e8f0;
    padding: 1.5rem;
    border-radius: 0.75rem;
    overflow-x: auto;
    margin: 1.5rem 0;
    border: 1px solid #334155;
}

.markdown-content pre code {
    background: transparent;
    color: inherit;
    padding: 0;
    border-radius: 0;
    font-weight: 400;
}

.markdown-content table {
    width: 100%;
    border-collapse: collapse;
    margin: 1.5rem 0;
    background: white;
    border-radius: 0.5rem;
    overflow: hidden;
    box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1);
}

.markdown-content th,
.markdown-content td {
    padding: 0.75rem 1rem;
    text-align: left;
    border-bottom: 1px solid #e2e8f0;
}

.markdown-content th {
    background: #f8fafc;
    font-weight: 600;
    color: #374151;
}

.markdown-content tr:hover {
    background: #f8fafc;
}

.markdown-content strong {
    font-weight: 700;
    color: #111827;
}

.markdown-content em {
    font-style: italic;
    color: #6b7280;
}

.markdown-content a {
    color: #3b82f6;
    text-decoration: underline;
    transition: color 0.2s ease;
}

.markdown-content a:hover {
    color: #1e40af;
}

.markdown-content hr {
    border: none;
    height: 2px;
    background: linear-gradient(to right, #e5e7eb, #9ca3af, #e5e7eb);
    margin: 2rem 0;
    border-radius: 1px;
}

/* Task Lists */
.markdown-content input[type="checkbox"] {
    margin-right: 0.5rem;
    transform: scale(1.2);
}

/* Animations */
@keyframes fade-in {
    from { opacity: 0; transform: translateY(20px); }
    to { opacity: 1; transform: translateY(0); }
}

@keyframes fade-in-up {
    from { opacity: 0; transform: translateY(30px); }
    to { opacity: 1; transform: translateY(0); }
}

@keyframes scale-in {
    from { opacity: 0; transform: scale(0.95); }
    to { opacity: 1; transform: scale(1); }
}

.animate-fade-in {
    animation: fade-in 0.6s ease-out;
}

.animate-fade-in-up {
    animation: fade-in-up 0.8s ease-out;
}

.animate-scale-in {
    animation: scale-in 0.5s ease-out;
}

.delay-100 {
    animation-delay: 0.1s;
}

.delay-200 {
    animation-delay: 0.2s;
}

/* Mobile Responsive */
@media (max-width: 768px) {
    .container {
        padding-left: 1rem;
        padding-right: 1rem;
    }
    
    .markdown-content {
        font-size: 0.95rem;
    }
    
    .markdown-content h1 {
        font-size: 1.75rem;
    }
    
    .markdown-content h2 {
        font-size: 1.5rem;
    }
    
    .markdown-content h3 {
        font-size: 1.25rem;
    }
    
    .markdown-content h4 {
        font-size: 1.125rem;
    }
    
    .markdown-content pre {
        padding: 1rem;
        font-size: 0.875rem;
    }
    
    .markdown-content table {
        font-size: 0.875rem;
    }
    
    .markdown-content th,
    .markdown-content td {
        padding: 0.5rem 0.75rem;
    }
    
    .flex-col {
        gap: 0.5rem;
    }
}

/* Loading Animation for Dynamic Content */
.loading-shimmer {
    background: linear-gradient(90deg, #f0f0f0 25%, #e0e0e0 50%, #f0f0f0 75%);
    background-size: 200% 100%;
    animation: shimmer 1.5s infinite;
}

@keyframes shimmer {
    0% { background-position: 200% 0; }
    100% { background-position: -200% 0; }
}

/* Dark mode support for code blocks */
@media (prefers-color-scheme: dark) {
    .markdown-content pre {
        background: #0f172a;
        border-color: #1e293b;
    }
}
</style>
@endsection